name: Check HTTP status code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check http status code of production site
      uses: lakuapik/gh-actions-http-status@v1
      with:
        sites: '["http://github.com"]'
        expected: '[301, 200]'
